# Project information
site_name: 'FactionsUUID'
site_description: 'Premium Factions for premium people.'
site_author: 'MOSS'
site_url: 'https://factions.support/'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/drtshock/Factions'
edit_uri: 'edit/1.6.x/docs/'

# Copyright
copyright: 'Copyright &copy; 2019-2020 MOSS'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

# Page tree
nav:
  - Home: index.md
  - Support: help.md
  - Introduction: introduction.md
  - Definitions: definitions.md
  - First Steps: firststeps.md
  - Commands: commands.md
  - Permissions: permissions.md
  - Permission Nodes: permissionnodes.md
  - Permission Contexts: contexts.md
  - Placeholders: placeholders.md
  - PlaceholderAPI: placeholderapi.md
  - Particles: particles.md
  - Developers: developers.md

# Customization
extra:
  social:
    - type: 'globe'
      link: 'https://discord.gg/PHpuzZS'

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
